---
title: "Assignment 1"
author: "Stephen Giang"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prob6}
# Problem 6, Exercise 2.1:

t <- seq(2015,2018, length = 100)
y1 <- function(t) sin(2*pi*(t - .1))
y2 <- function(t) (cos(2*pi*t))^2

plot (t,y1(t), 'l', col='blue', ylab='Functions', xlab = 'Time', 
      main = 'Functions over Time' ,panel.first=grid())
lines(t,y2(t), 'l', col='red')

text <- c(expression(y[1] == sin(2 *pi* (t - .1))),expression(y[2] == cos^2*(2*pi*t)))
legend('topright', legend=text , text.width = strwidth(text)[1]*1.2 , 
       col=c('blue','red') , lty=1 , cex=1 )
```

```{r prob7}
# Problem 7, Exercise 2.4

A <- matrix(c(-3, -2, 2, 2, -1, 1, 1 , 1, -4),nrow= 3)
b <- matrix(c(1, 2, 0))
x <- solve(A,b)

printAnswer <- c(paste('x =',x[1]),paste('y =',x[2]),paste('z =',x[3]))
matrix(printAnswer)
```

```{r prob8}
# Problem 8, Exercise 2.5

setwd('C:/Users/Stephen Giang/Documents/Math336Files/data')
readData <- read.csv('CA042239T.csv')

readData <- readData[85:dim(readData)[1],]
readData$TMAX..F. <- as.numeric(readData$TMAX..F.)
readData$TMEAN..F. <- as.numeric(readData$TMEAN..F.)
readData$TMIN..F. <- as.numeric(readData$TMIN..F.)


organize <- function(readData, yearStart, yearEnd, colNum) {
  rowStart <- 1 + 12*(yearStart - readData$YEAR[1])
  rowEnd <- 1 + 12*(yearEnd - readData$YEAR[1]) + 11
  
  dataRow <- matrix( c(readData[rowStart:(rowStart+11),colNum]),nrow=1)
  dataMatrix <- dataRow
  
  rowSeq <- seq((rowStart+12), rowEnd, by=12)
  for (row in rowSeq) {
    dataRow <- matrix( c(readData[row:(row+11),colNum]),nrow=1)
    dataMatrix <- rbind(dataMatrix, dataRow)
  }
  
  colnames(dataMatrix) <- c('Jan','Feb', 'Mar',
                           'Apr', 'May', 'Jun',
                           'Jul', 'Aug', 'Sep',
                           'Oct', 'Nov', 'Dec')
  
  
  return(dataMatrix)
}


PartA <- organize(readData, 1961, 1990, 4) #TMAX
PartA
PartB <- organize(readData, 1961, 1990, 6) #TMIN
PartB
PartC <- organize(readData, 1961, 1990, 5) #TMEAN
PartC


```


```{r prob9}
#Problem 9, Exercise 2.7

setwd('C:/Users/Stephen Giang/Documents/Math336Files/data')
readData <- read.csv('CA042239T.csv')

readData <- readData[85:dim(readData)[1],]
readData$TMAX..F. <- as.numeric(readData$TMAX..F.)
readData$TMEAN..F. <- as.numeric(readData$TMEAN..F.)
readData$TMIN..F. <- as.numeric(readData$TMIN..F.)


TMinMatrix <- function(readData, yearStart, yearEnd) {
  rowStart <- 1 + 12*(yearStart - readData$YEAR[1])
  rowEnd <- 1 + 12*(yearEnd - readData$YEAR[1]) + 11
  
  yearCol <- matrix( c( readData[rowStart:rowEnd, 2] + 
                          ((readData[rowStart:rowEnd, 3] - 1) / 12) ), ncol=1 )
  TMinCol <- matrix( c( readData[rowStart:rowEnd, 6]), ncol=1 )
  
  dataMatrix <- yearCol
  dataMatrix <- cbind(dataMatrix, TMinCol)
  
  return(dataMatrix)
}

slope <- seq(0,0,len=4)
slopeCount <- 1
colorList <- c('black', 'red','blue','green','yellow')
colorCount <- 2

TMinVals <- TMinMatrix(readData, 1951, 2010)
plot(TMinVals[,1], TMinVals[,2], 'l', xlab='Year',ylab='Minimum Temperature', 
     main='Minimum Temperature per Year', col= colorList[1], ylim=range(35,42))


yearStartSeq <- seq(1951, 1981, by=10)
for (yearStart in yearStartSeq) {
  TMinVals <- TMinMatrix(readData, yearStart, 2010)
  x <- TMinVals[,1]
  y <- TMinVals[,2]
  linMod <- lm(y~x)
  abline(linMod, col=colorList[colorCount])
  slope[slopeCount] <- linMod$coefficients[2]
  slopeCount <- slopeCount + 1
  colorCount <- colorCount + 1
}


text <- c( '1951 - 2010 TMIN', '1951 - 2010 TrendLine', '1961 - 2010 TrendLine', 
           '1971 - 2010 TrendLine', '1981 - 2010 TrendLine')
legend('topleft', legend=text , col=colorList , lty=1, cex=1)

printPartC <- c(paste('Slope for 1951-2010 TrendLine:',slope[1]), 
                paste('Slope for 1961-2010 TrendLine:',slope[2]), 
                paste('Slope for 1971-2010 TrendLine:',slope[3]), 
                paste('Slope for 1981-2010 TrendLine:',slope[4]))
matrix(printPartC)

```

```{r prob10}
#Problem 10, Exercise 2.9

setwd('C:/Users/Stephen Giang/Documents/Math336Files/data')
readData <- read.csv('NOAAGlobalT.csv')

t <- seq(1880,2017, by=(1/12))
y1 <- readData[1800,4:dim(readData)[2]]
y2 <- readData[1810,4:dim(readData)[2]]

plot(t, y1, 'l',col='red',ylab = 'Temperature', xlab = 'Year' ,
     main = 'Temperature Anomaly Time Series')
lines(t, y2, 'l',col='blue')

text <- c('Lat: 32.5, Lon: 357.5', 'Lat: 37.5, Lon: 47.5')
legend('topleft', legend = text, col = c('red','blue'), lty=1, cex=1)


```


