---
title: "MidtermCode"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Problem 4i

A = matrix( c(-1, -1.5, 2.2, 2.9, -1, 1, 1, 1, -4), nrow = 3)
b = matrix( c(1, 2.1, 0), ncol = 1)
X = solve(A,b)
sprintf("x = %.4f", X[1]) # x = -2.2117
sprintf("y = %.4f", X[2]) # y = 0.0015
sprintf("z = %.4f", X[3]) # z = -1.2161
```

```{r}
# Problem 4ii
setwd('C:/Users/Stephen Giang/Documents/Math336Files')
readData = read.csv('EarthTemperatureData.csv')

xvals = as.numeric(readData$YEAR)
yvals = as.numeric(readData$JUN)
plot(xvals, yvals, 'l', col = 'purple', lwd = 5, 
     xlab = 'Year', ylab = 'Temperature [deg C]', 
     main = 'Stephen Giang\'s plot of June temperature anomalies')

linmod = lm(yvals ~ xvals)
abline(linmod, col = 'blue', lwd = 3)

slope = linmod$coefficients[2] * 100 # .4525051
text(1900, 0.4, 'June trend = 0.45 deg C/ century ')


```


















